// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with the Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2f1u6Bf2i9PggwbKqEc8UMKOjcmtW13s',
    appId: '1:243083114409:web:b47bd621cf62ff5043b6b8',
    messagingSenderId: '243083114409',
    projectId: 'edulink-347ff',
    authDomain: 'edulink-347ff.firebaseapp.com',
    storageBucket: 'edulink-347ff.firebasestorage.app',
    measurementId: 'G-HZWDR8WYPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAytAhumAoj9a6nOB9MbVZPwHH8FVrec7A',
    appId: '1:243083114409:android:54daf970371a00a143b6b8',
    messagingSenderId: '243083114409',
    projectId: 'edulink-347ff',
    storageBucket: 'edulink-347ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOe_Z6iwXV1UgQd8vWETx3OUMXRqILKoU',
    appId: '1:243083114409:ios:cd0697a03668e0f543b6b8',
    messagingSenderId: '243083114409',
    projectId: 'edulink-347ff',
    storageBucket: 'edulink-347ff.firebasestorage.app',
    iosBundleId: 'com.example.edulinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOe_Z6iwXV1UgQd8vWETx3OUMXRqILKoU',
    appId: '1:243083114409:ios:cd0697a03668e0f543b6b8',
    messagingSenderId: '243083114409',
    projectId: 'edulink-347ff',
    storageBucket: 'edulink-347ff.firebasestorage.app',
    iosBundleId: 'com.example.edulinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2f1u6Bf2i9PggwbKqEc8UMKOjcmtW13s',
    appId: '1:243083114409:web:79fbec22550d864c43b6b8',
    messagingSenderId: '243083114409',
    projectId: 'edulink-347ff',
    authDomain: 'edulink-347ff.firebaseapp.com',
    storageBucket: 'edulink-347ff.firebasestorage.app',
    measurementId: 'G-BY682NK5D3',
  );
}
